# Generated by Django 5.0.6 on 2024-07-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_rename_talkbag_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
